site_title = "MyArxiv"
limit_days = 30
cache_url = "https://zhangshaolei1998.github.io/MyArxiv/cache.json"

[[sources]]
limit = 150
category = "cs.CL"
title = "Computation and Language"

[[sources]]
limit = 150
category = "cs.CV"
title = "Computer Vision and Pattern Recognition"

[[sources]]
limit = 150
category = "eess.AS"
title = "Audio and Speech Processing"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
